function report()
{
     var score=0;
    if(document.getElementById('ans1').checked)
    {
        score++;
    }
    if(document.getElementById('ans2').checked)
    {
        score++;
    }
    if(document.getElementById('ans3').checked)
    {
        score++;
    }
    if(document.getElementById('ans4').checked)
    {
        score++;
    }
    if(document.getElementById('ans5').checked)
    {
        score++;
    }
    if(document.getElementById('ans6').checked)
    {
        score++;
    }
    if(document.getElementById('ans7').checked)
    {
        score++;
    }
    if(document.getElementById('ans8').checked)
    {
        score++;
    }
    if(document.getElementById('ans9').checked)
    {
        score++;
    }
    if(document.getElementById('ans10').checked)
    {
        score++;
    }
    if(document.getElementById('ans11').checked)
    {
        score++;
    }
    if(document.getElementById('ans12').checked)
    {
        score++;
    }
    if(document.getElementById('ans13').checked)
    {
        score++;
    }
    if(document.getElementById('ans14').checked)
    {
        score++;
    }
    if(document.getElementById('ans15').checked)
    {
        score++;
    }
    if(document.getElementById('ans16').checked)
    {
        score++;
    }
    if(document.getElementById('ans17').checked)
    {
        score++;
    }
    if(document.getElementById('ans18').checked)
    {
        score++;
    }
    if(document.getElementById('ans19').checked)
    {
        score++;
    }
    if(document.getElementById('ans20').checked)
    {
        score++;
    }
    if(document.getElementById('ans21').checked)
    {
        score++;
    }
    if(document.getElementById('ans22').checked)
    {
        score++;
    }
    if(document.getElementById('ans23').checked)
    {
        score++;
    }
    if(document.getElementById('ans24').checked)
    {
        score++;
    }
    if(document.getElementById('ans25').checked)
    {
        score++;
    }
    if(document.getElementById('ans26').checked)
    {
        score++;
    }
    if(document.getElementById('ans27').checked)
    {
        score++;
    }
    if(document.getElementById('ans28').checked)
    {
        score++;
    }
    if(document.getElementById('ans29').checked)
    {
        score++;
    }
    if(document.getElementById('ans30').checked)
    {
        score++;
    }
    if(document.getElementById('ans31').checked)
    {
        score++;
    }
    if(document.getElementById('ans32').checked)
    {
        score++;
    }
    if(document.getElementById('ans33').checked)
    {
        score++;
    }
    if(document.getElementById('ans34').checked)
    {
        score++;
    }
    if(document.getElementById('ans35').checked)
    {
        score++;
    }
    if(document.getElementById('ans36').checked)
    {
        score++;
    }
    if(document.getElementById('ans37').checked)
    {
        score++;
    }
    if(document.getElementById('ans38').checked)
    {
        score++;
    }
    if(document.getElementById('ans39').checked)
    {
        score++;
    }
    if(document.getElementById('ans40').checked)
    {
        score++;
    }
    if(document.getElementById('ans41').checked)
    {
        score++;
    }
    if(document.getElementById('ans42').checked)
    {
        score++;
    }
    if(document.getElementById('ans43').checked)
    {
        score++;
    }
    if(document.getElementById('ans44').checked)
    {
        score++;
    }
    if(document.getElementById('ans45').checked)
    {
        score++;
    }
    if(document.getElementById('ans46').checked)
    {
        score++;
    }
    if(document.getElementById('ans47').checked)
    {
        score++;
    }
    if(document.getElementById('ans48').checked)
    {
        score++;
    }
    if(document.getElementById('ans49').checked)
    {
        score++;
    }
    if(document.getElementById('ans50').checked)
    {
        score++;
    }
        alert("Your score is"+score);
}
function myFunction() {
	location.replace("Online_Test_checker.html")
}